name: Test Automation

on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]
    schedule:
        - cron: '0 0 * * *' # Every day at midnight UTC

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.9, 3.10]
                test-suite: [smoke, api, regression]
                include:
                    - test-suite: smoke
                      args: "-m smoke"
                    - test-suite: api
                      args: "-m api"
                    - test-suite: regression
                      args: "-m 'not api'"
        steps:
        - uses: actions/checkout@v3

        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}
        
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
        - name: Install Chrome
          uses: browser-actions/setup-chrome@latest
        
        - name: Install ChromeDriver
          uses: nanasess/setup-chromedriver@master
        
        - name: Run tests
          run:
            pytest ${{ matrix.args }} --headless --browser=chrome --html=reports/report.html
        
        - name: Upload test report
          uses: actions/upload-artifact@v3
          if: always()
          with:
            name: test-report-${{ matrix.test-suite }}
            path: reports/